# Generated by Django 5.0.2 on 2024-02-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_order_total_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='prduct',
            new_name='product',
        ),
    ]
